services:
  db:
    image: postgres:15-alpine
    ports:
      - "54346:5432"
    environment:
      POSTGRES_DB: haal-centraal-auth-test
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: password
